language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements_dev.txt
script:
  - pycodestyle --show-pep8 *.py ./sqlmigman/*.py ./tests/*.py
  - pytest -vv --showlocals ./tests
